# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/droid2/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libmoto_gps.so:obj/lib/libmoto_gps.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libarcsoft.so:obj/lib/libarcsoft.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/liba2dp.so:obj/lib/liba2dp.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libaudio.so:obj/lib/libaudio.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libaudiopolicy.so:obj/lib/libaudiopolicy.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libnmea.so:obj/lib/libnmea.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libril_rds.so:obj/lib/libril_rds.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/librds_util.so:obj/lib/librds_util.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libsmiledetect.so:obj/lib/libsmiledetect.so
#    vendor/motorola/droid2/proprietary/lib/hw/gralloc.omap3.so:obj/lib/hw/gralloc.omap3.so

PRODUCT_COPY_FILES += \
   vendor/b00sted/proprietary/droid2/proprietary/app/FMRadio.apk:/system/app/FMRadio.apk \
   vendor/b00sted/proprietary/droid2/proprietary/app/FMRadioService.apk:/system/app/FMRadioService.apk \
   vendor/b00sted/proprietary/droid2/proprietary/app/PhoneConfig.apk:/system/app/PhoneConfig.apk \
   vendor/b00sted/proprietary/droid2/proprietary/app/ProgramMenu.apk:/system/app/ProgramMenu.apk \
   vendor/b00sted/proprietary/droid2/proprietary/app/ProgramMenuSystem.apk:/system/app/ProgramMenuSystem.apk \

# All the blobs necessary for droid2
PRODUCT_COPY_FILES += \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libmoto_gps.so:/system/lib/libmoto_gps.so \
   vendor/b00sted/proprietary/droid2/proprietary/bin/Hostapd:/system/bin/Hostapd \
   vendor/b00sted/proprietary/droid2/proprietary/bin/SaveBPVer:/system/bin/SaveBPVer \
   vendor/b00sted/proprietary/droid2/proprietary/bin/akmd2:/system/bin/akmd2 \
   vendor/b00sted/proprietary/droid2/proprietary/bin/ap_gain.bin:/system/bin/ap_gain.bin \
   vendor/b00sted/proprietary/droid2/proprietary/bin/ap_gain_mmul.bin:/system/bin/ap_gain_mmul.bin \
   vendor/b00sted/proprietary/droid2/proprietary/bin/batch:/system/bin/batch \
   vendor/b00sted/proprietary/droid2/proprietary/bin/battd:/system/bin/battd \
   vendor/b00sted/proprietary/droid2/proprietary/bin/btcmd:/system/bin/btcmd \
   vendor/b00sted/proprietary/droid2/proprietary/bin/bthelp:/system/bin/bthelp \
   vendor/b00sted/proprietary/droid2/proprietary/bin/bttest_mot:/system/bin/bttest_mot \
   vendor/b00sted/proprietary/droid2/proprietary/bin/chat-ril:/system/bin/chat-ril \
   vendor/b00sted/proprietary/droid2/proprietary/bin/dbvc_atvc_property_set:/system/bin/dbvc_atvc_property_set \
   vendor/b00sted/proprietary/droid2/proprietary/bin/dmt:/system/bin/dmt \
   vendor/b00sted/proprietary/droid2/proprietary/bin/dund:/system/bin/dund \
   vendor/b00sted/proprietary/droid2/proprietary/bin/ecckeyd:/system/bin/ecckeyd \
   vendor/b00sted/proprietary/droid2/proprietary/bin/fdisk:/system/bin/fdisk \
   vendor/b00sted/proprietary/droid2/proprietary/bin/firewall.sh:/system/bin/firewall.sh \
   vendor/b00sted/proprietary/droid2/proprietary/bin/fmradioserver:/system/bin/fmradioserver \
   vendor/b00sted/proprietary/droid2/proprietary/bin/ftmipcd:/system/bin/ftmipcd \
   vendor/b00sted/proprietary/droid2/proprietary/bin/gkilogd:/system/bin/gkilogd \
   vendor/b00sted/proprietary/droid2/proprietary/bin/loadpreinstalls.sh:/system/bin/loadpreinstalls.sh \
   vendor/b00sted/proprietary/droid2/proprietary/bin/mdm_panicd:/system/bin/mdm_panicd \
   vendor/b00sted/proprietary/droid2/proprietary/bin/napics.sh:/system/bin/napics.sh \
   vendor/b00sted/proprietary/droid2/proprietary/bin/pppd:/system/bin/pppd \
   vendor/b00sted/proprietary/droid2/proprietary/bin/pppd-ril:/system/bin/pppd-ril \
   vendor/b00sted/proprietary/droid2/proprietary/bin/secclkd:/system/bin/secclkd \
   vendor/b00sted/proprietary/droid2/proprietary/bin/smc_pa_ctrl:/system/bin/smc_pa_ctrl \
   vendor/b00sted/proprietary/droid2/proprietary/bin/smoduled:/system/bin/smoduled \
   vendor/b00sted/proprietary/droid2/proprietary/bin/startup_smc.sh:/system/bin/startup_smc.sh \
   vendor/b00sted/proprietary/droid2/proprietary/bin/tcmd:/system/bin/tcmd \
   vendor/b00sted/proprietary/droid2/proprietary/bin/testpppd:/system/bin/testpppd \
   vendor/b00sted/proprietary/droid2/proprietary/bin/tstmetainfo:/system/bin/tstmetainfo \
   vendor/b00sted/proprietary/droid2/proprietary/bin/usbd:/system/bin/usbd \
   vendor/b00sted/proprietary/droid2/proprietary/etc/amazon-kindle.properties:/system/etc/amazon-kindle.properties \
   vendor/b00sted/proprietary/droid2/proprietary/etc/backup_targets.csv:/system/etc/backup_targets.csv \
   vendor/b00sted/proprietary/droid2/proprietary/etc/cameraCalFileDef5M.bin:/system/etc/cameraCalFileDef5M.bin \
   vendor/b00sted/proprietary/droid2/proprietary/etc/excluded-input-devices.xml:/system/etc/excluded-input-devices.xml \
   vendor/b00sted/proprietary/droid2/proprietary/etc/firmware/ap_bt_data.bin:/system/etc/firmware/ap_bt_data.bin \
   vendor/b00sted/proprietary/droid2/proprietary/etc/firmware/wl1271.bin:/system/etc/firmware/wl1271.bin \
   vendor/b00sted/proprietary/droid2/proprietary/etc/fm_rx_init_1273.2.bts:/system/etc/fm_rx_init_1273.2.bts \
   vendor/b00sted/proprietary/droid2/proprietary/etc/fm_rx_init_6450.2.bts:/system/etc/fm_rx_init_6450.2.bts \
   vendor/b00sted/proprietary/droid2/proprietary/etc/fmc_init_1273.2.bts:/system/etc/fmc_init_1273.2.bts \
   vendor/b00sted/proprietary/droid2/proprietary/etc/fmc_init_6450.2.bts:/system/etc/fmc_init_6450.2.bts \
   vendor/b00sted/proprietary/droid2/proprietary/etc/pppd-ril.options:/system/etc/ppp/peers/pppd-ril.options \
   vendor/b00sted/proprietary/droid2/proprietary/etc/priority_notifications_config.xml:/system/etc/priority_notifications_config.xml \
   vendor/b00sted/proprietary/droid2/proprietary/etc/mancacerts.zip:/system/etc/security/mancacerts.zip \
   vendor/b00sted/proprietary/droid2/proprietary/etc/oprcacerts.zip:/system/etc/security/oprcacerts.zip \
   vendor/b00sted/proprietary/droid2/proprietary/etc/suplcerts.bks:/system/etc/security/suplcerts.bks \
   vendor/b00sted/proprietary/droid2/proprietary/etc/smc_android_cfg.ini:/system/etc/smc_android_cfg.ini \
   vendor/b00sted/proprietary/droid2/proprietary/etc/smc_android_cfg_256.ini:/system/etc/smc_android_cfg_256.ini \
   vendor/b00sted/proprietary/droid2/proprietary/etc/smc_pa.ift:/system/etc/smc_pa.ift \
   vendor/b00sted/proprietary/droid2/proprietary/etc/smc_pa_pk_4_ipa.bin:/system/etc/smc_pa_pk_4_ipa.bin \
   vendor/b00sted/proprietary/droid2/proprietary/etc/supportedlocales.conf:/system/etc/supportedlocales.conf \
   vendor/b00sted/proprietary/droid2/proprietary/etc/vzwpubagps.cer:/system/etc/vzwpubagps.cer \
   vendor/b00sted/proprietary/droid2/proprietary/etc/wifi/fw_tiwlan_ap.bin:/system/etc/wifi/fw_tiwlan_ap.bin \
   vendor/b00sted/proprietary/droid2/proprietary/etc/wifi/fw_wlan1271.bin:/system/etc/wifi/fw_wlan1271.bin \
   vendor/b00sted/proprietary/droid2/proprietary/etc/wifi/hostapd.conf.templet:/system/etc/wifi/hostapd.conf.templet \
   vendor/b00sted/proprietary/droid2/proprietary/etc/wifi/tiwlan.ini:/system/etc/wifi/tiwlan.ini \
   vendor/b00sted/proprietary/droid2/proprietary/etc/wifi/tiwlan_ap.ini:/system/etc/wifi/tiwlan_ap.ini \
   vendor/b00sted/proprietary/droid2/proprietary/etc/wifi/wpa_supplicant.conf:/system/etc/wifi/wpa_supplicant.conf \
   vendor/b00sted/proprietary/droid2/proprietary/lib/dsp/baseimage.dof:/system/lib/dsp/baseimage.dof \
   vendor/b00sted/proprietary/droid2/proprietary/lib/dsp/conversions.dll64P:/system/lib/dsp/conversions.dll64P \
   vendor/b00sted/proprietary/droid2/proprietary/lib/dsp/h264vdec_sn.dll64P:/system/lib/dsp/h264vdec_sn.dll64P \
   vendor/b00sted/proprietary/droid2/proprietary/lib/dsp/h264venc_sn.dll64P:/system/lib/dsp/h264venc_sn.dll64P \
   vendor/b00sted/proprietary/droid2/proprietary/lib/dsp/jpegenc_sn.dll64P:/system/lib/dsp/jpegenc_sn.dll64P \
   vendor/b00sted/proprietary/droid2/proprietary/lib/dsp/m4venc_sn.dll64P:/system/lib/dsp/m4venc_sn.dll64P \
   vendor/b00sted/proprietary/droid2/proprietary/lib/dsp/mp3dec_sn.dll64P:/system/lib/dsp/mp3dec_sn.dll64P \
   vendor/b00sted/proprietary/droid2/proprietary/lib/dsp/mp4vdec_sn.dll64P:/system/lib/dsp/mp4vdec_sn.dll64P \
   vendor/b00sted/proprietary/droid2/proprietary/lib/dsp/mpeg4aacdec_sn.dll64P:/system/lib/dsp/mpeg4aacdec_sn.dll64P \
   vendor/b00sted/proprietary/droid2/proprietary/lib/dsp/mpeg4aacenc_sn.dll64P:/system/lib/dsp/mpeg4aacenc_sn.dll64P \
   vendor/b00sted/proprietary/droid2/proprietary/lib/dsp/nbamrdec_sn.dll64P:/system/lib/dsp/nbamrdec_sn.dll64P \
   vendor/b00sted/proprietary/droid2/proprietary/lib/dsp/nbamrenc_sn.dll64P:/system/lib/dsp/nbamrenc_sn.dll64P \
   vendor/b00sted/proprietary/droid2/proprietary/lib/dsp/postprocessor_dualout.dll64P:/system/lib/dsp/postprocessor_dualout.dll64P \
   vendor/b00sted/proprietary/droid2/proprietary/lib/dsp/ringio.dll64P:/system/lib/dsp/ringio.dll64P \
   vendor/b00sted/proprietary/droid2/proprietary/lib/dsp/usn.dll64P:/system/lib/dsp/usn.dll64P \
   vendor/b00sted/proprietary/droid2/proprietary/lib/dsp/wbamrdec_sn.dll64P:/system/lib/dsp/wbamrdec_sn.dll64P \
   vendor/b00sted/proprietary/droid2/proprietary/lib/dsp/wbamrenc_sn.dll64P:/system/lib/dsp/wbamrenc_sn.dll64P \
   vendor/b00sted/proprietary/droid2/proprietary/lib/dsp/wmadec_sn.dll64P:/system/lib/dsp/wmadec_sn.dll64P \
   vendor/b00sted/proprietary/droid2/proprietary/lib/dsp/wmv9dec_sn.dll64P:/system/lib/dsp/wmv9dec_sn.dll64P \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libWifiAPHardware.so:/system/lib/libWifiAPHardware.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libarcsoftpe.so:/system/lib/libarcsoftpe.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libarcsoft.so:/system/lib/libarcsoft.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libbattd.so:/system/lib/libbattd.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libcaps.so:/system/lib/libcaps.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libcryptoki.so:/system/lib/libcryptoki.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libdmengine.so:/system/lib/libdmengine.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libdmjavaplugin.so:/system/lib/libdmjavaplugin.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libglslcompiler.so:/system/lib/libglslcompiler.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libhostapd_client.so:/system/lib/libhostapd_client.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libimage_jni.so:/system/lib/libimage_jni.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libjanus.so:/system/lib/libjanus.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libjanus_jni.so:/system/lib/libjanus_jni.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libmediaext.so:/system/lib/libmediaext.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libmetainfo.so:/system/lib/libmetainfo.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libmot_atcmd.so:/system/lib/libmot_atcmd.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libmot_atcmd_mflex.so:/system/lib/libmot_atcmd_mflex.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libmot_bluetooth_jni.so:/system/lib/libmot_bluetooth_jni.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libmot_btpan_jni.so:/system/lib/libmot_btpan_jni.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libmot_led.so:/system/lib/libmot_led.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libmotdrm1.so:/system/lib/libmotdrm1.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libmotdrm1_jni.so:/system/lib/libmotdrm1_jni.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libmoto_netutil.so:/system/lib/libmoto_netutil.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libmoto_ril.so:/system/lib/libmoto_ril.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libmotodbgutils.so:/system/lib/libmotodbgutils.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libmtp_jni.so:/system/lib/libmtp_jni.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libmtpstack.so:/system/lib/libmtpstack.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libnativedrm1.so:/system/lib/libnativedrm1.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libOMX.TI.720P.Decoder.so:/system/lib/libOMX.TI.720P.Decoder.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libOMX.TI.720P.Encoder.so:/system/lib/libOMX.TI.720P.Encoder.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/liboemcamera.so:/system/lib/liboemcamera.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libpanorama.so:/system/lib/libpanorama.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libpanorama_jni.so:/system/lib/libpanorama_jni.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libpkip.so:/system/lib/libpkip.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libpppd_plugin.so:/system/lib/libpppd_plugin.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libprojectM.so:/system/lib/libprojectM.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libprovlib.so:/system/lib/libprovlib.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libscalado.so:/system/lib/libscalado.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libsmapi.so:/system/lib/libsmapi.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libssmgr.so:/system/lib/libssmgr.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libtpa.so:/system/lib/libtpa.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libtpa_core.so:/system/lib/libtpa_core.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libui3d.so:/system/lib/libui3d.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libvideoeditorlite.so:/system/lib/libvideoeditorlite.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libwbxmlparser.so:/system/lib/libwbxmlparser.so \
   vendor/b00sted/proprietary/droid2/proprietary/tts/lang_pico/en-US_lh0_sg.bin:/system/tts/lang_pico/en-US_lh0_sg.bin \
   vendor/b00sted/proprietary/droid2/proprietary/tts/lang_pico/en-US_ta.bin:/system/tts/lang_pico/en-US_ta.bin \
   vendor/b00sted/proprietary/droid2/proprietary/tts/lang_pico/es-ES_ta.bin:/system/tts/lang_pico/es-ES_ta.bin \
   vendor/b00sted/proprietary/droid2/proprietary/tts/lang_pico/es-ES_zl0_sg.bin:/system/tts/lang_pico/es-ES_zl0_sg.bin \
   vendor/b00sted/proprietary/droid2/proprietary/xbin/backup:/system/xbin/backup \
   vendor/b00sted/proprietary/droid2/proprietary/xbin/drm1_func_test:/system/xbin/drm1_func_test \
   vendor/b00sted/proprietary/droid2/proprietary/xbin/run_backup:/system/xbin/run_backup \
   vendor/b00sted/proprietary/droid2/proprietary/xbin/run_restore:/system/xbin/run_restore \
   vendor/b00sted/proprietary/droid2/proprietary/xbin/ssmgrd:/system/xbin/ssmgrd \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libaudio.so:/system/lib/libaudio.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libcamera.so:/system/lib/libcamera.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libnmea.so:/system/lib/libnmea.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libril_rds.so:/system/lib/libril_rds.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/librds_util.so:/system/lib/librds_util.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libsmiledetect.so:/system/lib/libsmiledetect.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libbridge.so:/system/lib/libbridge.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libmoto_ril.so:/system/lib/libmoto_ril.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libpppd_plugin-ril.so:/system/lib/libpppd_plugin-ril.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libbattd.so:/system/lib/libattd.so \
   vendor/b00sted/proprietary/droid2/proprietary/bin/battd.so:/system/bin/battd \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libusc.so:/system/lib/libusc.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libFMRadio.so:system/lib/libFMRadio.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libfmradio_jni.so:system/lib/libfmradio_jni.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/libfmradioplayer.so:system/lib/libfmradioplayer.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/hw/lights.droid2.so:/system/lib/hw/lights.droid2.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/hw/sensors.droid2.so:/system/lib/hw/sensors.droid2.so \
   vendor/b00sted/proprietary/droid2/proprietary/lib/hw/gps.droid2.so:/system/lib/hw/gps.droid2.so 

